### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by kirtan0000** [cirosantilli/test-many-commits-1m#11]
Can you please tell how do I do this?

**Comment by cirosantilli** [comment]
See repo description.

**Comment by cirosantilli** [comment]
What are you really truly honestly 12? Do you have any big projects/areas of interest in mind?

**Comment by kirtan0000** [comment]
Yes, I am actually 12. I just wanna try this. I'm just curious. Whenever I run the python n file, it gives me an error saying "invalid literal for int() with base 10"

**Comment by cirosantilli** [comment]
I don't reproduce on master at ad7e205d2460ef2239d1bf8048ec0c36ecf3ef8a Python 3.8.6 e.g. with:

```
./many-commits-fast-import.py 10
```

**Comment by kirtan0000** [comment]
I type in:
`$ python ../many-commits-fast-import.py [ncommits=10] | git fast-import`
and then it gives the error: `Traceback (most recent call last):
fatal: Unsupported command: blob
fast-import: dumping crash report to .git/fast_import_crash_16220
  File "C:\Users\kirta\OneDrive\Documents\test\many-commits-fast-import.py", line 29, in <module>
    n = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: '[ncommits=10]'`

**Comment by kirtan0000** [comment]
Wait, nvm, 
`python many-commits-fast-import.py 10`
works lol

**Comment by kirtan0000** [comment]
Nvm,
when i type:
`% python ../many-commits-fast-import.py 10 | git fast-import`
it says:
`fatal: Unsupported command: 
fast-import: dumping crash report to .git/fast_import_crash_9924`

**Comment by cirosantilli** [comment]
When reporting bugs, you have to give the version of your software, and search if that might be the problem.

I have `git --version`:

```
git version 2.30.0
```

and:

```
rm -rf many-commits.tmp
mkdir -p many-commits.tmp
cd many-commits.tmp
git init
../many-commits-fast-import.py [ncommits=10] | git fast-import
```

worked now.

**Comment by kirtan0000** [comment]
I guess its because your on Linux and I'm on windows.

brb I'm gonna go to Linux

**Comment by cirosantilli** [comment]
It should work on Windows, just make sure your git is new enough.

But yes, just don't use Windows.

**Comment by kirtan0000** [comment]
On Ubuntu 20.10 ARM, it says:
`bash: ../many-commits-fast-import.py: Permission denied
/usr/lib/git-core/git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2399 KiB
       pools:          2048 KiB
     objects:           351 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
`

**Comment by kirtan0000** [comment]
I used sudo

**Comment by kirtan0000** [comment]
nvm, i just used chmod and it works, but now it says

`../many-commits-fast-import.py: line 1: import: command not found
../many-commits-fast-import.py: line 14: syntax error near unexpected token `$'\'\'\'blob\nmark :1\ndata 1\na\nreset refs/heads/master\ncommit refs/heads/master\nmark :2\nauthor  <> 0 +0000\ncommitter  <> 0 +0000\ndata 1\nM 100644 :1 a\n\'\'\'''
../many-commits-fast-import.py: line 14: `''')'
`

**Comment by kirtan0000** [comment]
nvm, i type:
`python3 ../many-commits-fast-import.py 10 | git fast-import`
and it works, but it says:
`fatal: Unsupported command:  100644 :1 a
fast-import: dumping crash report to .git/fast_import_crash_4491
Unpacking objects: 100% (3/3), 116 bytes | 116.00 KiB/s, done.
`

**Comment by kirtan0000** [comment]
when i push, it only shows 1 commit: https://github.com/kirtan0000/a-lot-of-commits
i give up lol, this is useless like u said

**Comment by cirosantilli** [comment]
The last failure I don't understand why it's happening. I can't reproduce unfortunately. One day, one day who knows.
