### ISSUE TITLE
Competition 

### ISSUE THREAD

**Issue by ghost** [cirosantilli/test-many-commits-1m#12]
Hey,
Let's have a small competition.
`https://github.com/complexorganizations/git-commits-generator` VS `https://github.com/cirosantilli/test-many-commits-1m`

Let's create some rules.

```
1. Validate all commits by GPG
2. All commits must be public
3. All commits must include a commit message
4. All commits must be validated by github
5. All commits must be legit.
```

Here are some rules suggestions.

**Comment by cirosantilli** [comment]
Hi Prajwal,

Does signing commits add any particular "this might break GitHub" type quirkiness? E.g. did the repo stall forever after upload while it verified commits?

Are you just using `git config --global user.signingkey` or doing something fancier? It would be slightly interesting to learn how to sign from Python to do it with fast import, but not interesting enough for me to do it :-)

**Comment by ghost** [comment]
1. No, There is no delay, (Like not even 1 ms)
2. Yes, that's just fine.

Also do u have any suggestions for any rules change?

**Comment by cirosantilli** [comment]
OK. Sorry but I don't think that this is very interesting. If you do something and something cool/unexpected happens, do ping me though!

**Comment by ghost** [comment]
> OK. Sorry but I don't think that this is very interesting. If you do something and something cool/unexpected happens, do ping me though!

For me the GUI (repo) won't work properly.
Almost past 2M commits, should be able to get more commits than this repo today.

**Comment by cirosantilli** [comment]
About number of commits, the generation procedure of this repo is super fast for any number of commits, and the repo size per commit is the smallest I can find. I could easily push much larger repos. But they will start hitting GitHub's 1GB max repo size. Let me know if you achieve any advances in those areas (generation speed/repo sizer per commit).

**Comment by ghost** [comment]
1. I didn't even know GitHub has a 1GB max repo size. (I am 99% sure its 100GB) (1GB Per / 1M Legit Valid Commits)
2. Not really, the method your using is not generating legit commits, it more like spoofing.
3. I mean you can always spin up a server and than let it run for a couple of days and than push all the commits at once.
4. One more thing, Git sees that your `.git` folder is spoofed and won't really work, you might just want to generate legit commits.
5. A while back there was a method for generating git commits in like seconds, where you could generate 100m commits but i think git patched it, all the old accounts who used it, it just shows that they have no commits.

**Comment by Prajwal-Koirala** [comment]
@cirosantilli
Don't try and save data by removing metadata, and instead just do a normal commit.

Also use my script and it will generate about 10M/commits per day if ur machine can handle it. (I recommend manually pushing it every 100k)

**Comment by Prajwal-Koirala** [comment]
Hey @cirosantill

Check out my repo, after about 6M commits it gives u an infinite logo
