### ISSUE TITLE
You have been overtaken by 1,000,004 commits

### ISSUE THREAD

**Issue by ghost** [cirosantilli/test-many-commits-1m#13]
https://github.com/virejdasani/Commited

**Comment by ghost** [comment]
oh no

**Comment by cirosantilli** [comment]
Generation time and size per commit is all that matters, I could easily generate a 10M repo.

**Comment by ghost** [comment]
*Interesting*

**Comment by ghost** [comment]
@GrpeApple
https://github.com/complexorganizations/git-commits-generator

6M+ validated commits.

**Comment by ghost** [comment]
> @GrpeApple
> https://github.com/complexorganizations/git-commits-generator
> 
> 6M+ validated commits.

At this point, the contribution graph is broken.

**Comment by ghost** [comment]
@GrpeApple
Hey,
The GitHub automated system banned me, a while ago; lol.
I will try and get to 100M commits.
- Prajwal

**Comment by that-dude-with-free-time** [comment]
yolo i have 4m
